// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Event struct {
	ID        int32
	Message   sql.NullString
	CreatedAt time.Time
	Severity  sql.NullString
}
